# Build final output & push to Cachix on main
name: ğŸš€ Build & Push to Cachix

on:
  push:
    branches:
      - main

jobs:
  build:
    name: ğŸ—ï¸ Build & Upload
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ğŸ§Š Install Nix
        uses: cachix/install-nix-action@v25

      - name: ğŸ·ï¸ Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: schrovimger
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: ğŸ”¨ Build .#default
        run: nix build .#default --system x86_64-linux

      - name: ğŸ“¤ Push to Cachix
        run: cachix push schrovimger ./result
